### ISSUE TITLE
addcurve()->setcurve() 

### ISSUE THREAD

**Issue by ichrys03** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#240]
**Describe the bug**
 Answer 1,1 instead of 1,3? (CurveNvalue-> points on the curve) 

**Screenshots**

![435018160_3658286057716576_4390027296330355944_n](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/assets/79056704/dc230e34-804e-4572-8f48-fc667bb1ec1e)

**Comment by Mariosmsk** [comment]
The function looks ok.

You need to use the following assignment:

`values = [x_y_1; x_y_2; x_y_3];` 

Make sure to use semicolons instead of commas.

So, I will close this issue and the corresponding pull request #245 

![image](https://github.com/user-attachments/assets/ba6ef1e5-0c08-4e86-adf0-a79117b4a29a)
